# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlod/protos/kitti_utils.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()


from mlod.protos import mini_batch_pb2 as mlod_dot_protos_dot_mini__batch__pb2


DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlod/protos/kitti_utils.proto',
  package='mlod.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x1dmlod/protos/kitti_utils.proto\x12\x0bmlod.protos\x1a\x1cmlod/protos/mini_batch.proto\"\xdd\x01\n\x10KittiUtilsConfig\x12\x14\n\x0c\x61rea_extents\x18\x01 \x03(\x02\x12\x12\n\nvoxel_size\x18\x02 \x02(\x02\x12\x16\n\x0e\x61nchor_strides\x18\x03 \x03(\x02\x12\x1c\n\x11\x64\x65nsity_threshold\x18\x04 \x01(\x05:\x01\x31\x12\x30\n\rbev_generator\x18\x14 \x02(\x0b\x32\x19.mlod.protos.BevGenerator\x12\x37\n\x11mini_batch_config\x18\x15 \x02(\x0b\x32\x1c.mlod.protos.MiniBatchConfig\"\xc2\x02\n\x0c\x42\x65vGenerator\x12?\n\rheight_priors\x18\x01 \x01(\x0b\x32&.mlod.protos.BevGenerator.HeightPriorsH\x00\x12\x32\n\x06slices\x18\x02 \x01(\x0b\x32 .mlod.protos.BevGenerator.SlicesH\x00\x1ah\n\x0cHeightPriors\x12\x1c\n\x14ground_filter_offset\x18\x01 \x02(\x02\x12\x1e\n\x16offset_filter_distance\x18\x02 \x02(\x02\x12\x1a\n\x12std_dev_multiplier\x18\x03 \x02(\x02\x1a\x42\n\x06Slices\x12\x11\n\theight_lo\x18\x01 \x02(\x02\x12\x11\n\theight_hi\x18\x02 \x02(\x02\x12\x12\n\nnum_slices\x18\x03 \x02(\x05\x42\x0f\n\rbev_maps_type')
  ,
  dependencies=[mlod_dot_protos_dot_mini__batch__pb2.DESCRIPTOR,])
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_KITTIUTILSCONFIG = _descriptor.Descriptor(
  name='KittiUtilsConfig',
  full_name='mlod.protos.KittiUtilsConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='area_extents', full_name='mlod.protos.KittiUtilsConfig.area_extents', index=0,
      number=1, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='voxel_size', full_name='mlod.protos.KittiUtilsConfig.voxel_size', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='anchor_strides', full_name='mlod.protos.KittiUtilsConfig.anchor_strides', index=2,
      number=3, type=2, cpp_type=6, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='density_threshold', full_name='mlod.protos.KittiUtilsConfig.density_threshold', index=3,
      number=4, type=5, cpp_type=1, label=1,
      has_default_value=True, default_value=1,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='bev_generator', full_name='mlod.protos.KittiUtilsConfig.bev_generator', index=4,
      number=20, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mini_batch_config', full_name='mlod.protos.KittiUtilsConfig.mini_batch_config', index=5,
      number=21, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=77,
  serialized_end=298,
)


_BEVGENERATOR_HEIGHTPRIORS = _descriptor.Descriptor(
  name='HeightPriors',
  full_name='mlod.protos.BevGenerator.HeightPriors',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ground_filter_offset', full_name='mlod.protos.BevGenerator.HeightPriors.ground_filter_offset', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='offset_filter_distance', full_name='mlod.protos.BevGenerator.HeightPriors.offset_filter_distance', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='std_dev_multiplier', full_name='mlod.protos.BevGenerator.HeightPriors.std_dev_multiplier', index=2,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=434,
  serialized_end=538,
)

_BEVGENERATOR_SLICES = _descriptor.Descriptor(
  name='Slices',
  full_name='mlod.protos.BevGenerator.Slices',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height_lo', full_name='mlod.protos.BevGenerator.Slices.height_lo', index=0,
      number=1, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='height_hi', full_name='mlod.protos.BevGenerator.Slices.height_hi', index=1,
      number=2, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='num_slices', full_name='mlod.protos.BevGenerator.Slices.num_slices', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=540,
  serialized_end=606,
)

_BEVGENERATOR = _descriptor.Descriptor(
  name='BevGenerator',
  full_name='mlod.protos.BevGenerator',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='height_priors', full_name='mlod.protos.BevGenerator.height_priors', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='slices', full_name='mlod.protos.BevGenerator.slices', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[_BEVGENERATOR_HEIGHTPRIORS, _BEVGENERATOR_SLICES, ],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='bev_maps_type', full_name='mlod.protos.BevGenerator.bev_maps_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=301,
  serialized_end=623,
)

_KITTIUTILSCONFIG.fields_by_name['bev_generator'].message_type = _BEVGENERATOR
_KITTIUTILSCONFIG.fields_by_name['mini_batch_config'].message_type = mlod_dot_protos_dot_mini__batch__pb2._MINIBATCHCONFIG
_BEVGENERATOR_HEIGHTPRIORS.containing_type = _BEVGENERATOR
_BEVGENERATOR_SLICES.containing_type = _BEVGENERATOR
_BEVGENERATOR.fields_by_name['height_priors'].message_type = _BEVGENERATOR_HEIGHTPRIORS
_BEVGENERATOR.fields_by_name['slices'].message_type = _BEVGENERATOR_SLICES
_BEVGENERATOR.oneofs_by_name['bev_maps_type'].fields.append(
  _BEVGENERATOR.fields_by_name['height_priors'])
_BEVGENERATOR.fields_by_name['height_priors'].containing_oneof = _BEVGENERATOR.oneofs_by_name['bev_maps_type']
_BEVGENERATOR.oneofs_by_name['bev_maps_type'].fields.append(
  _BEVGENERATOR.fields_by_name['slices'])
_BEVGENERATOR.fields_by_name['slices'].containing_oneof = _BEVGENERATOR.oneofs_by_name['bev_maps_type']
DESCRIPTOR.message_types_by_name['KittiUtilsConfig'] = _KITTIUTILSCONFIG
DESCRIPTOR.message_types_by_name['BevGenerator'] = _BEVGENERATOR

KittiUtilsConfig = _reflection.GeneratedProtocolMessageType('KittiUtilsConfig', (_message.Message,), dict(
  DESCRIPTOR = _KITTIUTILSCONFIG,
  __module__ = 'mlod.protos.kitti_utils_pb2'
  # @@protoc_insertion_point(class_scope:mlod.protos.KittiUtilsConfig)
  ))
_sym_db.RegisterMessage(KittiUtilsConfig)

BevGenerator = _reflection.GeneratedProtocolMessageType('BevGenerator', (_message.Message,), dict(

  HeightPriors = _reflection.GeneratedProtocolMessageType('HeightPriors', (_message.Message,), dict(
    DESCRIPTOR = _BEVGENERATOR_HEIGHTPRIORS,
    __module__ = 'mlod.protos.kitti_utils_pb2'
    # @@protoc_insertion_point(class_scope:mlod.protos.BevGenerator.HeightPriors)
    ))
  ,

  Slices = _reflection.GeneratedProtocolMessageType('Slices', (_message.Message,), dict(
    DESCRIPTOR = _BEVGENERATOR_SLICES,
    __module__ = 'mlod.protos.kitti_utils_pb2'
    # @@protoc_insertion_point(class_scope:mlod.protos.BevGenerator.Slices)
    ))
  ,
  DESCRIPTOR = _BEVGENERATOR,
  __module__ = 'mlod.protos.kitti_utils_pb2'
  # @@protoc_insertion_point(class_scope:mlod.protos.BevGenerator)
  ))
_sym_db.RegisterMessage(BevGenerator)
_sym_db.RegisterMessage(BevGenerator.HeightPriors)
_sym_db.RegisterMessage(BevGenerator.Slices)


# @@protoc_insertion_point(module_scope)
