# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: mlod/protos/mini_batch.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
from google.protobuf import descriptor_pb2
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='mlod/protos/mini_batch.proto',
  package='mlod.protos',
  syntax='proto2',
  serialized_pb=_b('\n\x1cmlod/protos/mini_batch.proto\x12\x0bmlod.protos\"\x8c\x02\n\x0fMiniBatchConfig\x12\x19\n\x11\x64\x65nsity_threshold\x18\x01 \x02(\x05\x12\x33\n\nrpn_config\x18\x02 \x02(\x0b\x32\x1f.mlod.protos.MiniBatchRpnConfig\x12\x37\n\x0erpn_img_config\x18\x03 \x02(\x0b\x32\x1f.mlod.protos.MiniBatchRpnConfig\x12\x35\n\x0bmlod_config\x18\x04 \x02(\x0b\x32 .mlod.protos.MiniBatchMlodConfig\x12\x39\n\x0fmlod_img_config\x18\x05 \x02(\x0b\x32 .mlod.protos.MiniBatchMlodConfig\"h\n\x16MiniBatchIouThresholds\x12\x12\n\nneg_iou_lo\x18\x03 \x02(\x02\x12\x12\n\nneg_iou_hi\x18\x04 \x02(\x02\x12\x12\n\npos_iou_lo\x18\x05 \x02(\x02\x12\x12\n\npos_iou_hi\x18\x06 \x02(\x02\"\xbd\x01\n\x12MiniBatchRpnConfig\x12@\n\x11iou_2d_thresholds\x18\x01 \x01(\x0b\x32#.mlod.protos.MiniBatchIouThresholdsH\x00\x12@\n\x11iou_3d_thresholds\x18\x02 \x01(\x0b\x32#.mlod.protos.MiniBatchIouThresholdsH\x00\x12\x17\n\x0fmini_batch_size\x18\x03 \x02(\x05\x42\n\n\x08iou_type\"n\n\x13MiniBatchMlodConfig\x12>\n\x11iou_2d_thresholds\x18\x01 \x02(\x0b\x32#.mlod.protos.MiniBatchIouThresholds\x12\x17\n\x0fmini_batch_size\x18\x02 \x02(\x05')
)
_sym_db.RegisterFileDescriptor(DESCRIPTOR)




_MINIBATCHCONFIG = _descriptor.Descriptor(
  name='MiniBatchConfig',
  full_name='mlod.protos.MiniBatchConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='density_threshold', full_name='mlod.protos.MiniBatchConfig.density_threshold', index=0,
      number=1, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpn_config', full_name='mlod.protos.MiniBatchConfig.rpn_config', index=1,
      number=2, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='rpn_img_config', full_name='mlod.protos.MiniBatchConfig.rpn_img_config', index=2,
      number=3, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mlod_config', full_name='mlod.protos.MiniBatchConfig.mlod_config', index=3,
      number=4, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mlod_img_config', full_name='mlod.protos.MiniBatchConfig.mlod_img_config', index=4,
      number=5, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=46,
  serialized_end=314,
)


_MINIBATCHIOUTHRESHOLDS = _descriptor.Descriptor(
  name='MiniBatchIouThresholds',
  full_name='mlod.protos.MiniBatchIouThresholds',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='neg_iou_lo', full_name='mlod.protos.MiniBatchIouThresholds.neg_iou_lo', index=0,
      number=3, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='neg_iou_hi', full_name='mlod.protos.MiniBatchIouThresholds.neg_iou_hi', index=1,
      number=4, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_iou_lo', full_name='mlod.protos.MiniBatchIouThresholds.pos_iou_lo', index=2,
      number=5, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='pos_iou_hi', full_name='mlod.protos.MiniBatchIouThresholds.pos_iou_hi', index=3,
      number=6, type=2, cpp_type=6, label=2,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=316,
  serialized_end=420,
)


_MINIBATCHRPNCONFIG = _descriptor.Descriptor(
  name='MiniBatchRpnConfig',
  full_name='mlod.protos.MiniBatchRpnConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iou_2d_thresholds', full_name='mlod.protos.MiniBatchRpnConfig.iou_2d_thresholds', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='iou_3d_thresholds', full_name='mlod.protos.MiniBatchRpnConfig.iou_3d_thresholds', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mini_batch_size', full_name='mlod.protos.MiniBatchRpnConfig.mini_batch_size', index=2,
      number=3, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
    _descriptor.OneofDescriptor(
      name='iou_type', full_name='mlod.protos.MiniBatchRpnConfig.iou_type',
      index=0, containing_type=None, fields=[]),
  ],
  serialized_start=423,
  serialized_end=612,
)


_MINIBATCHMLODCONFIG = _descriptor.Descriptor(
  name='MiniBatchMlodConfig',
  full_name='mlod.protos.MiniBatchMlodConfig',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='iou_2d_thresholds', full_name='mlod.protos.MiniBatchMlodConfig.iou_2d_thresholds', index=0,
      number=1, type=11, cpp_type=10, label=2,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
    _descriptor.FieldDescriptor(
      name='mini_batch_size', full_name='mlod.protos.MiniBatchMlodConfig.mini_batch_size', index=1,
      number=2, type=5, cpp_type=1, label=2,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      options=None),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  options=None,
  is_extendable=False,
  syntax='proto2',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=614,
  serialized_end=724,
)

_MINIBATCHCONFIG.fields_by_name['rpn_config'].message_type = _MINIBATCHRPNCONFIG
_MINIBATCHCONFIG.fields_by_name['rpn_img_config'].message_type = _MINIBATCHRPNCONFIG
_MINIBATCHCONFIG.fields_by_name['mlod_config'].message_type = _MINIBATCHMLODCONFIG
_MINIBATCHCONFIG.fields_by_name['mlod_img_config'].message_type = _MINIBATCHMLODCONFIG
_MINIBATCHRPNCONFIG.fields_by_name['iou_2d_thresholds'].message_type = _MINIBATCHIOUTHRESHOLDS
_MINIBATCHRPNCONFIG.fields_by_name['iou_3d_thresholds'].message_type = _MINIBATCHIOUTHRESHOLDS
_MINIBATCHRPNCONFIG.oneofs_by_name['iou_type'].fields.append(
  _MINIBATCHRPNCONFIG.fields_by_name['iou_2d_thresholds'])
_MINIBATCHRPNCONFIG.fields_by_name['iou_2d_thresholds'].containing_oneof = _MINIBATCHRPNCONFIG.oneofs_by_name['iou_type']
_MINIBATCHRPNCONFIG.oneofs_by_name['iou_type'].fields.append(
  _MINIBATCHRPNCONFIG.fields_by_name['iou_3d_thresholds'])
_MINIBATCHRPNCONFIG.fields_by_name['iou_3d_thresholds'].containing_oneof = _MINIBATCHRPNCONFIG.oneofs_by_name['iou_type']
_MINIBATCHMLODCONFIG.fields_by_name['iou_2d_thresholds'].message_type = _MINIBATCHIOUTHRESHOLDS
DESCRIPTOR.message_types_by_name['MiniBatchConfig'] = _MINIBATCHCONFIG
DESCRIPTOR.message_types_by_name['MiniBatchIouThresholds'] = _MINIBATCHIOUTHRESHOLDS
DESCRIPTOR.message_types_by_name['MiniBatchRpnConfig'] = _MINIBATCHRPNCONFIG
DESCRIPTOR.message_types_by_name['MiniBatchMlodConfig'] = _MINIBATCHMLODCONFIG

MiniBatchConfig = _reflection.GeneratedProtocolMessageType('MiniBatchConfig', (_message.Message,), dict(
  DESCRIPTOR = _MINIBATCHCONFIG,
  __module__ = 'mlod.protos.mini_batch_pb2'
  # @@protoc_insertion_point(class_scope:mlod.protos.MiniBatchConfig)
  ))
_sym_db.RegisterMessage(MiniBatchConfig)

MiniBatchIouThresholds = _reflection.GeneratedProtocolMessageType('MiniBatchIouThresholds', (_message.Message,), dict(
  DESCRIPTOR = _MINIBATCHIOUTHRESHOLDS,
  __module__ = 'mlod.protos.mini_batch_pb2'
  # @@protoc_insertion_point(class_scope:mlod.protos.MiniBatchIouThresholds)
  ))
_sym_db.RegisterMessage(MiniBatchIouThresholds)

MiniBatchRpnConfig = _reflection.GeneratedProtocolMessageType('MiniBatchRpnConfig', (_message.Message,), dict(
  DESCRIPTOR = _MINIBATCHRPNCONFIG,
  __module__ = 'mlod.protos.mini_batch_pb2'
  # @@protoc_insertion_point(class_scope:mlod.protos.MiniBatchRpnConfig)
  ))
_sym_db.RegisterMessage(MiniBatchRpnConfig)

MiniBatchMlodConfig = _reflection.GeneratedProtocolMessageType('MiniBatchMlodConfig', (_message.Message,), dict(
  DESCRIPTOR = _MINIBATCHMLODCONFIG,
  __module__ = 'mlod.protos.mini_batch_pb2'
  # @@protoc_insertion_point(class_scope:mlod.protos.MiniBatchMlodConfig)
  ))
_sym_db.RegisterMessage(MiniBatchMlodConfig)


# @@protoc_insertion_point(module_scope)
